#!/usr/bin/env ruby

require_relative 'lib/client'

trap(:INT) do
  puts "\nBye-bye"
  abort
end

Thread.abort_on_exception = true

client = Client.new
client.listen

loop { client.transmit(gets.chomp) }
